---
global:
templates:
- '/etc/alertmanager/template/*.tmpl'
route:
  repeat_interval: 1m
  receiver: xxxxxxxxxxx

receivers:
- name: 'xxxxxxxxxxx'
  slack_configs:
  - api_url: https://hooks.slack.com/services/xxxxxxxxxxx/xxxxxxxxxxx/xxxxxxxxxxx
    channel: '#xalert'
    send_resolved: true
